# Generated by Django 5.0.3 on 2024-03-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0002_remove_book_authors_author_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='empty'),
        ),
    ]
